"""workflow dossiers devis

Revision ID: 38f0f7f52fa5
Revises: f0eb4a71fe2c
Create Date: 2026-05-01 20:19:14.473638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f0f7f52fa5'
down_revision = 'f0eb4a71fe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers_reparation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('pending_devis', 'pending_approval', 'in_progress', 'paused_pending_approval', 'completed', 'cancelled', name='statut_dossier_reparation'), nullable=False),
    sa.Column('demande_client', sa.Text(), nullable=False),
    sa.Column('diagnostic_initial', sa.Text(), nullable=True),
    sa.Column('kilometrage_entree', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossiers_reparation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossiers_reparation_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dossiers_reparation_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_dossiers_reparation_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_dossiers_reparation_vehicule_id'), ['vehicule_id'], unique=False)

    op.create_table('devis_reparation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('pending', 'approved', 'rejected', name='statut_devis_reparation'), nullable=False),
    sa.Column('objet', sa.String(length=200), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mode_accord', sa.Enum('telephone', 'presentiel', 'systeme', name='mode_accord_devis'), nullable=True),
    sa.Column('accord_client', sa.Boolean(), nullable=False),
    sa.Column('accord_assurance', sa.Boolean(), nullable=False),
    sa.Column('approuve_le', sa.DateTime(), nullable=True),
    sa.Column('approuve_par_id', sa.Integer(), nullable=True),
    sa.Column('motif_refus', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approuve_par_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_reparation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'version', name='uq_devis_reparation_version')
    )
    with op.batch_alter_table('devis_reparation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devis_reparation_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('journal_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_reparation.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_actions_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('lignes_devis_reparation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prix_unitaire_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ht', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['devis_id'], ['devis_reparation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lignes_devis_reparation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_devis_reparation_devis_id'), ['devis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lignes_devis_reparation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_devis_reparation_devis_id'))

    op.drop_table('lignes_devis_reparation')
    with op.batch_alter_table('journal_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_actions_dossier_id'))

    op.drop_table('journal_actions')
    with op.batch_alter_table('devis_reparation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devis_reparation_dossier_id'))

    op.drop_table('devis_reparation')
    with op.batch_alter_table('dossiers_reparation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossiers_reparation_vehicule_id'))
        batch_op.drop_index(batch_op.f('ix_dossiers_reparation_statut'))
        batch_op.drop_index(batch_op.f('ix_dossiers_reparation_numero'))
        batch_op.drop_index(batch_op.f('ix_dossiers_reparation_client_id'))

    op.drop_table('dossiers_reparation')
    # ### end Alembic commands ###
