"""ajout clients vehicules

Revision ID: f0eb4a71fe2c
Revises: 0001_schema_initial
Create Date: 2026-04-30 22:08:56.143760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0eb4a71fe2c'
down_revision = '0001_schema_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('particulier', 'administration', 'sntl', name='type_client'), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('sigle', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('telephone_2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=50), nullable=True),
    sa.Column('ice', sa.String(length=20), nullable=True),
    sa.Column('if_fiscal', sa.String(length=20), nullable=True),
    sa.Column('rc', sa.String(length=20), nullable=True),
    sa.Column('administration_rattachee', sa.String(length=100), nullable=True),
    sa.Column('delai_paiement_jours', sa.Integer(), nullable=False),
    sa.Column('plafond_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_nom'), ['nom'], unique=False)

    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(length=30), nullable=False),
    sa.Column('type_immatriculation', sa.Enum('standard', 'administrative', 'ww', 'etranger', name='type_immatriculation'), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('couleur', sa.String(length=30), nullable=True),
    sa.Column('type_carburant', sa.Enum('essence', 'diesel', 'electrique', 'hybride', name='type_carburant'), nullable=True),
    sa.Column('type_vehicule', sa.Enum('voiture', 'utilitaire', 'camion', 'moto', 'engin', 'bateau', name='type_vehicule'), nullable=True),
    sa.Column('kilometrage_actuel', sa.Integer(), nullable=True),
    sa.Column('derniere_visite', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicules_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicules_immatriculation'), ['immatriculation'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicules_vin'), ['vin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicules_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicules_immatriculation'))
        batch_op.drop_index(batch_op.f('ix_vehicules_client_id'))

    op.drop_table('vehicules')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_nom'))
        batch_op.drop_index(batch_op.f('ix_clients_code'))

    op.drop_table('clients')
    # ### end Alembic commands ###
